### ISSUE TITLE
fixer.io API will be deprecated soon

### ISSUE THREAD

**Issue by TheBlackNarwhal** [BUYMERCIER/crypto-arbitrage#2]
The API will be deprecated, we need to find another way to use it as it will stop working.

![deprecated](https://user-images.githubusercontent.com/26217508/38583493-7afccd94-3d13-11e8-9da7-aec4e5ec5433.png)

**Comment by BUYMERCIER** [comment]
fixer.io started to commercialise their API.
We either need to find another free service or reduce our monthly hits to 1,000.

Will work on that
